spring:
  datasource:
    url: jdbc:mysql://124.71.96.96:3306/mcms_admin?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true
    username: root
    password: 123456
    filters: wall,mergeStat
    type: com.alibaba.druid.pool.DruidDataSource
